Ouvrir avec [Basthon](https://notebook.basthon.fr/?kernel=sql&from=https://raw.githubusercontent.com/thfruchart/tnsi/main/03/exemple.ipynb&module=https://raw.githubusercontent.com/thfruchart/tnsi/main/03/livres.sql)

## Notbook exemple : 
### base de données BIBLIOTHÈQUE

In [2]:
SELECT nom 
FROM auteur 
JOIN auteur_de ON auteur.a_id = auteur_de.a_id 
JOIN livre ON auteur_de.isbn = livre.isbn 
WHERE livre.titre= "Guerre et Paix";

nom
Tolstoï

In [3]:
SELECT titre 
FROM livre 
JOIN auteur_de ON auteur_de.isbn = livre.isbn 
JOIN auteur ON auteur.a_id = auteur_de.a_id 
WHERE nom="Tolstoï";

titre
La Mort d'Ivan Ilitch
Anna Karénine
Guerre et Paix

In [11]:
SELECT titre 
FROM livre 
JOIN auteur_de ON auteur_de.isbn = livre.isbn 
JOIN auteur ON auteur.a_id = auteur_de.a_id 
WHERE nom= (
    SELECT nom 
    FROM auteur 
    JOIN auteur_de ON auteur.a_id = auteur_de.a_id 
    JOIN livre ON auteur_de.isbn = livre.isbn 
    WHERE livre.titre= "Guerre et Paix");

titre
La Mort d'Ivan Ilitch
Anna Karénine
Guerre et Paix

In [5]:
SELECT titre FROM livre JOIN auteur_de ON auteur_de.isbn = livre.isbn JOIN auteur ON auteur.a_id = auteur_de.a_id WHERE nom IN (SELECT nom FROM auteur JOIN auteur_de ON auteur.a_id = auteur_de.a_id JOIN livre ON auteur_de.isbn = livre.isbn WHERE livre.titre= "Le Devin");

titre
Astérix chez les Pictes
Astérix chez les Pictes
Les Lauriers de César
Les Lauriers de César
Astérix et Cléopâtre
Astérix et Cléopâtre
Le Tour de Gaule d'Astérix
Le Tour de Gaule d'Astérix
Le Cadeau de César
Le Cadeau de César
Astérix et les Normands
Astérix et les Normands
Astérix en Corse
Astérix en Corse
Le Devin
Le Devin
Astérix légionnaire
Astérix légionnaire
L'Odyssée d'Astérix
Le Domaine des dieux
Le Domaine des dieux
Astérix chez les Bretons
Astérix chez les Bretons
Obélix et Compagnie
Obélix et Compagnie
Astérix chez les Belges
Astérix chez les Belges

In [12]:
SELECT titre FROM livre
WHERE isbn NOT IN 
(SELECT titre 
 FROM livre
 JOIN emprunt on emprunt.isbn = livre.isbn);

titre
Les Aventures de Huckleberry Finn
Fondation et Empire
Akira
Les Robots
Astérix chez les Pictes
Les Monades urbaines
Les Voyages de Gulliver
Lolita
La Nuit des temps
Ravage
Les Lauriers de César
Niourk
Le Meilleur des mondes
Berlin Alexanderplatz
Fahrenheit 451
La Mort d'Ivan Ilitch
Croisière sans escale
Le Vieil Homme et la Mer
Mrs Dalloway
L'Idiot
Le Carnet d'or
Les Grandes Espérances
Astérix et Cléopâtre
Madame Bovary
Les Frères Karamazov
Moby Dick
Demain les chiens
Le Tour de Gaule d'Astérix
1984
Don Quichotte
Le Château de Lord Valentin
Le Père Goriot
Le Procès
L'Homme qui rétrécit
Chroniques martiennes
Le Roi Lear
Le Cadeau de César
La Planète des singes
Orgueil et Préjugés
Une maison de poupée
Vermilion Sands
La Grande Traversée
L'Étranger
L'Île des morts
Par-delà le mur du sommeil
Le Papyrus de César
La Main de Zeï
Beloved
La Conscience de Zeno
Delirium Circus
Médée
Nostromo
Au carrefour des étoiles
Le Vagabond
Les Buddenbrook
Les Métamorphoses
Jack Barron et l'Éternité
Hacker's Delight
Astérix et les Normands
Le Temps incertain
Astérix en Corse
Les Fils de la Médina
Le Grand secret
Le Devin
Le Noir Dessein
Astérix légionnaire
Romancero gitano
The Practice of Programming
Crime et Châtiment
La Promenade au phare
L'Homme sans qualités
Le Bruit et la Fureur
Les Plus qu'humains
La Main gauche de la nuit
Mémoires d'Hadrien
Contes de l'absurde
Astérix et la Transitalique
L'Odyssée d'Astérix
Les Singes du temps
Les Contes de Canterbury
Sécheresse
The Art of Computer Programming
L'Aveuglement
Le Berceau du chat
Anna Karénine
La Montagne magique
Le Domaine des dieux
Cent ans de solitude
Gargantua et Pantagruel
Contes
Guerre et Paix
Énéide
Seconde Fondation
Les Jeux de l'esprit
Middlemarch
Œdipe roi
L'Amour aux temps du choléra
Fictions
Astérix chez les Bretons
Le Château
Le Voyageur imprudent
Je suis une légende
Le Maître du Haut Château
Les Âmes mortes
Le Tambour
Polymath
Seigneur de lumière
Ulysse
Pedro Páramo
Ubik
Algorithms
Fifi Brindacier
Le monde s'effondre
La Naissance des dieux
Hamlet
Les Enfants de minuit
Dune
La Couleur tombée du ciel
L'Éducation sentimentale
Obélix et Compagnie
Le Journal d'un fou
Les Hauts de Hurlevent
La Plaie
Astérix chez les Belges
Le Rouge et le Noir
À la recherche du temps perdu
La storia
L'Homme total